"""Fresh development banks under alternative noise configurations.

The generator is the pilot generator with the observation-noise covariance and
shared-bias covariance as explicit parameters; with the pilot values it
reproduces `research.simulation.generate_bank` exactly (tested). Banks receive
new identifiers and seeds. The scientific reservation is refused by construction.
"""
from __future__ import annotations

import json
import math

import numpy as np
import pandas as pd
from scipy.stats import multivariate_normal

from research.data import RAW_FIELDS
from research.simulation import (CONDITIONS, PRIOR_VARIANCE, disk_probability, disk_probability_check,
                                 posterior, windows)
from research.simulation_v2 import repair_bank

# Scientific evaluation seed plus the ten V03 training-bank seeds; identifiers
# with these prefixes are reserved for the frozen Track R scientific run.
RESERVED_SEEDS = frozenset({20261012, *range(20261301, 20261311)})
RESERVED_PREFIXES = ('scientific', 'scitrain')
AVAILABILITY = np.r_[np.linspace(8., 6.1, 60), np.linspace(1., .1, 20)]


def noise_covariance(eigenvalues, rotation_degrees: float) -> np.ndarray:
    """Q diag(eigenvalues) Q^T; refuses non-positive or non-finite variances."""
    values = np.asarray(eigenvalues, dtype=float)
    if values.shape != (2,) or not np.isfinite(values).all() or np.any(values <= 0) or not math.isfinite(rotation_degrees):
        raise ValueError('Expected two positive finite variances and a finite rotation')
    angle = math.radians(rotation_degrees)
    q = np.array([[math.cos(angle), -math.sin(angle)], [math.sin(angle), math.cos(angle)]])
    covariance = q @ np.diag(values) @ q.T
    # Symmetrize and normalize signed zeros so a zero rotation equals the pilot's R exactly.
    covariance = (covariance + covariance.T) / 2
    covariance = np.where(covariance == 0, 0., covariance)
    if np.any(np.linalg.eigvalsh(covariance) <= 0):
        raise ValueError('Noise covariance is not positive definite')
    return covariance


class ReservedAccess:
    """Permission for named reserved banks; issued only after a frozen-protocol check."""

    def __init__(self, protocol_sha256: str, banks: dict[str, int]):
        if len(protocol_sha256) != 64 or not banks:
            raise ValueError('Reserved access needs a protocol hash and named banks')
        self.protocol_sha256, self.banks = protocol_sha256, dict(banks)

    def permits(self, bank: str, seed: int) -> bool:
        return self.banks.get(bank) == seed


def check_identity(bank: str, seed: int, access: ReservedAccess | None = None) -> None:
    if seed in RESERVED_SEEDS or bank.startswith(RESERVED_PREFIXES):
        if not (isinstance(access, ReservedAccess) and access.permits(bank, seed)):
            raise ValueError('The scientific reservation cannot be generated by development code')


def generate_config_bank(n: int, seed: int, bank: str, noise: np.ndarray, shared_bias: np.ndarray,
                         access: ReservedAccess | None = None):
    """Pilot generator with explicit R and B; same random-call order as the pilot."""
    check_identity(bank, seed, access)
    rng = np.random.default_rng(seed)
    R, B = np.asarray(noise, dtype=float), np.asarray(shared_bias, dtype=float)
    messages, lineage, cohort = [], [], []
    for i in range(n):
        sid = f'{bank}:{i:05d}'
        enriched = rng.random() < .3
        x = rng.normal(0, .12 if enriched else 1.5, size=2)
        bias = rng.multivariate_normal(np.zeros(2), B)
        obs = x + bias + rng.multivariate_normal(np.zeros(2), R, size=80)
        final_mean, final_covariance = posterior(obs, R, B)
        final_risk = float(np.log10(max(disk_probability(final_mean, final_covariance), 1e-30)))
        target_density = multivariate_normal.pdf(x, cov=np.eye(2) * PRIOR_VARIANCE)
        proposal_density = .7 * target_density + .3 * multivariate_normal.pdf(x, cov=np.eye(2) * .12 ** 2)
        cohort.append({'series_id': sid, 'final_risk': final_risk, 'mission_id': bank,
                       'sampling_weight_to_wide_gaussian': float(target_density / proposal_density),
                       'enriched_component': enriched, 'shared_bias': bool(np.any(B != 0))})
        for condition in CONDITIONS:
            for j, (indices, tau) in enumerate(zip(windows(condition), np.linspace(6., 2., 6))):
                assert np.all(AVAILABILITY[indices] >= tau)
                # The experimental estimator ignores shared bias; the final-label oracle does not.
                mean, covariance = posterior(obs[indices], R)
                pc = disk_probability(mean, covariance)
                row = {name: 0. for name in RAW_FIELDS}
                row.update(series_id=sid, condition=condition, risk=float(np.log10(max(pc, 1e-30))),
                           time_to_tca=float(tau), miss_distance=float(np.linalg.norm(mean)), relative_speed=0.)
                age = float(AVAILABILITY[indices].min() - tau)
                bounds = (0., 1.) if age < 1 else ((1., 2.) if age < 2 else (2., 180.))
                for role in ('t', 'c'):
                    row[f'{role}_sigma_r'] = float(np.sqrt(covariance[0, 0] / 2))
                    row[f'{role}_sigma_t'] = float(np.sqrt(covariance[1, 1] / 2))
                    row[f'{role}_sigma_n'] = 0.
                    row[f'{role}_obs_available'] = 60.
                    row[f'{role}_obs_used'] = float(len(indices))
                    row[f'{role}_actual_od_span'] = float(np.ptp(AVAILABILITY[indices]))
                    row[f'{role}_recommended_od_span'] = 1.
                    row[f'{role}_residuals_accepted'] = 100.
                    row[f'{role}_weighted_rms'] = float(np.sqrt(np.mean((obs[indices] - mean) ** 2) / (np.trace(R) / 2)))
                    row[f'{role}_time_lastob_end'], row[f'{role}_time_lastob_start'] = bounds
                messages.append(row)
                lineage.append({'series_id': sid, 'condition': condition, 'message_index': j,
                                'observation_ids': json.dumps(indices.tolist()), 'available_at_tca_days': float(tau),
                                'source_solution_id': ','.join(map(str, indices))})
                if condition == 'exact_replay':
                    messages.extend([row.copy(), row.copy()])
    return pd.DataFrame(cohort), pd.DataFrame(messages), pd.DataFrame(lineage)


def cadence_bank(n: int, seed: int, bank: str, noise: np.ndarray, shared_bias: np.ndarray,
                 access: ReservedAccess | None = None):
    """Generate, then apply the audited V02 cadence repair (adds burst reissue)."""
    cohort, messages, lineage = generate_config_bank(n, seed, bank, noise, shared_bias, access)
    repaired, membership = repair_bank(messages, lineage)
    return cohort, repaired, membership


def integration_check(noise: np.ndarray, seed: int, samples: int = 200, rtol: float = 1e-6, atol: float = 1e-11) -> dict:
    """Compare production disk integration with an independent quadrature on drawn posteriors."""
    rng = np.random.default_rng(seed)
    worst_abs = worst_rel = 0.
    for _ in range(samples):
        x = rng.normal(0, .12 if rng.random() < .5 else 1.5, size=2)
        size = int(rng.choice([10, 60, 80]))
        obs = x + rng.multivariate_normal(np.zeros(2), noise, size=size)
        mean, covariance = posterior(obs, noise)
        a, b = disk_probability(mean, covariance), disk_probability_check(mean, covariance)
        worst_abs = max(worst_abs, abs(a - b))
        if b >= 1e-8:  # relative error is reported where probabilities are near or above the 1e-6 label threshold
            worst_rel = max(worst_rel, abs(a - b) / b)
        if not np.isclose(a, b, rtol=rtol, atol=atol):
            raise ValueError(f'Disk integration disagreement: {a} versus {b}')
    return {'samples': samples, 'max_abs_difference': worst_abs, 'max_rel_difference': worst_rel,
            'relative_error_floor': 1e-8, 'rtol': rtol, 'atol': atol, 'covariance_eigenvalues': np.linalg.eigvalsh(noise).tolist()}
